Optimize Chinese Translation
Wurst-Imperium/Wurst7 pull request #1043
Opened 2024-07-24 13:57 UTC by OutHimic

原有的中文翻译文件实在是不太符合中国人的习惯，我建议优化一下，方便理解。
这是我自己花一个下午制作的翻译文件，你们可以看一下，求被应用！

The current Chinese translation may not fully align with the natural language usage and preferences of native Chinese speakers. I would like to propose an optimized version to improve comprehensibility and user experience. Enclosed is a translation file that I have personally prepared over the course of an afternoon. I kindly request that you review it and consider its implementation.

## Description
> What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)

## Testing
> How have you tested your changes? Any testing tips for the reviewer?

## References
> List any related issues, forum posts, videos and such here.

2024-07-24 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=1043) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=1043) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=1043) it.</sub>

2024-07-24 15:39 UTC, Alexander01998 requested changes
Hey @OutHimic, thanks for the PR!

This seems to be quite a big change, modifying almost every translation string and adding many new ones. Please bear with me as it might take a while to fully review all of that.

At first glance, I do see a few issues that would need to be fixed before we can merge this:
- In previous discussions with other translators, I'm pretty sure we agreed to always use `。`, `，`, etc. in the Chinese translations, instead of `.`, `,`, etc.
- There should also be spaces around any English words and after punctuation, like how it was in the previous version. This makes it easier to read in-game.
- While you've correctly kept most of the names in English, I do see a few issues like "NoChatReports" being translated to "无聊天报告".

Also, please remember to [sign the CLA](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=1043) so that the changes can be merged.

Tagging previous translators in case they would like to comment on this PR: @MuelsyseKen @Clexus @FeyXieXzf @MineYuanlu

---

嘿 @OutHimic，感谢您的 PR！

这似乎是一个相当大的改动，几乎修改了所有的翻译字符串并添加了许多新字符串。请耐心等待，因为我可能需要一段时间才能完全审核所有内容。

乍一看，我确实发现有几个问题需要在合并之前解决：
- 在之前与其他译者的讨论中，我确定我们同意在中文翻译中始终使用`。`、`、`等，而不是`.`、`,`等。
- 此外，任何英文单词周围和标点符号后都应该有空格，就像以前的版本一样。这样在游戏中更容易阅读。
- 虽然您正确地保留了大部分英文名称，但我还是发现了一些问题，比如 “NoChatReports ”被翻译成了 “无聊天报告”。

此外，请记得 [在 CLA 上签名](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=1043)，以便合并修改。

标记之前的译者，以防他们对此 PR 发表评论： @MuelsyseKen @Clexus @FeyXieXzf @MineYuanlu

2024-07-25 02:50 UTC, Clexus commented
我指出以下几点不足：
1. 你可以在描述里单开一行给这个功能加一个翻译，但是你必须使用正式一点的译名，这里不是给你玩梗造词的地方，很多人会用到这些翻译，给它们一个正式名称
2. 不要用机翻，不要用不标准的译名。我多次看到将弩翻译为十字弓，将重锤翻译为战锤的翻译，请你亲自去对照标准译名列表修改，还有一些东西很明显使用了机翻，翻译是一项严肃的工作，使用机翻是其中最令人厌恶也最令人恶心的行为，你将一个mod的名字翻译成中文，请问你的意欲何为？
3. 在你不知道的领域，尊重其他译者。你为什么要将一些原本意思没有任何问题的翻译改成自己的，而且有些还有很多错误？Big Brother指的是《1984》之中的老大哥，翻译过来就如此，你改成英文是什么意思？

2024-07-25 03:00 UTC, OutHimic commented
> 我指出以下几点不足：
> 
> 1. 你可以在描述里单开一行给这个功能加一个翻译，但是你必须使用正式一点的译名，这里不是给你玩梗造词的地方，很多人会用到这些翻译，给它们一个正式名称
> 2. 不要用机翻，不要用不标准的译名。我多次看到将弩翻译为十字弓，将重锤翻译为战锤的翻译，请你亲自去对照标准译名列表修改，还有一些东西很明显使用了机翻，翻译是一项严肃的工作，使用机翻是其中最令人厌恶也最令人恶心的行为，你将一个mod的名字翻译成中文，请问你的意欲何为？
> 3. 在你不知道的领域，尊重其他译者。你为什么要将一些原本意思没有任何问题的翻译改成自己的，而且有些还有很多错误？Big Brother指的是《1984》之中的老大哥，翻译过来就如此，你改成英文是什么意思？

抱歉，我并没有注意到这几点。我会尽快重新检查我的翻译，给出更好的版本的。感谢你们的重视！

Sorry, I didn't notice that. I will recheck my translation as soon as possible to give a better version. Thank you for your attention！

2024-07-25 03:04 UTC, Clexus commented
> > 我指出以下几点不足：
> > 
> > 1. 你可以在描述里单开一行给这个功能加一个翻译，但是你必须使用正式一点的译名，这里不是给你玩梗造词的地方，很多人会用到这些翻译，给它们一个正式名称
> > 2. 不要用机翻，不要用不标准的译名。我多次看到将弩翻译为十字弓，将重锤翻译为战锤的翻译，请你亲自去对照标准译名列表修改，还有一些东西很明显使用了机翻，翻译是一项严肃的工作，使用机翻是其中最令人厌恶也最令人恶心的行为，你将一个mod的名字翻译成中文，请问你的意欲何为？
> > 3. 在你不知道的领域，尊重其他译者。你为什么要将一些原本意思没有任何问题的翻译改成自己的，而且有些还有很多错误？Big Brother指的是《1984》之中的老大哥，翻译过来就如此，你改成英文是什么意思？
> 
> 抱歉，我并没有注意到这几点。我会尽快重新检查我的翻译，给出更好的版本的。感谢你们的重视！
> 
> Sorry, I didn't notice that. I will recheck my translation as soon as possible to give a better version. Thank you for your attention！

我对我的评论进行了更新，我不想骂你，但是从你的提交可以看出你的自大和对其他译者的不尊重

2024-08-25 19:45 UTC, closed without merging