ColorSetting implementation
Wurst-Imperium/Wurst7 pull request #455
Opened 2021-08-08 09:49 UTC by hiddenalt-team

## Description
ColorSetting implementation described in issue #292 
- Replaced AC & BG options with ColorSettings. 
- Added ColorSetting with click-to-edit color preview button. _No lock(), isLocked() and setCheckedIgnoreLock() functions were implemented yet. Alpha channel selection is not implemented for now (may be in future pull request)._
- Added EditColorScreen with RGB input fields and clickable color palette. After changes applied the setting is saved in json as string in RGB CSV format (example: "255,128,0").
- Added basic .setcolor cmd _(untested by me yet, including CheckboxSetting.getPossibleKeybinds())_

## (Optional) screenshots / videos
https://user-images.githubusercontent.com/69734595/128627362-898d93c5-e02d-4896-b287-0f0f805ca502.mp4

2021-08-08 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=455) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=455) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=455) it.</sub>

2021-08-20 17:31 UTC, WrightModzz requested changes
Nice, please add wurst copyright info

2021-08-20 17:32 UTC, WrightModzz commented
Oops, gimme a sec

2021-08-20 17:52 UTC, hiddenalt-team commented
> 
> 
> Oops, gimme a sec

Ok, so I can add the copyright manually or should I do something else?

2021-09-06 19:39 UTC, merged