Fix all the grammar problem,improve text and more.
Wurst-Imperium/Wurst7 pull request #491
Opened 2021-11-10 12:36 UTC by SistineFibelKen

According to the #488 request I fix all the grammar problem and improve text and more. If you from Mainland China and want to improve the translations please contact me frist. thanks.

E-mail：yu2221038595@163.com

2021-11-12 04:49 UTC, SistineFibelKen commented
@Alexander01998 😋 Don't forget it ~

2021-11-12 07:04 UTC, Alexander01998 requested changes
😅 Here you go. @SistineFibelKen

2021-11-12 07:15 UTC, SistineFibelKen commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.bonemealaura": "在指定的作物上自动使用骨粉。\n使用 Checkboxes 来指定作物。",
is it the Checkboxes likes Minecraft Debug tools?

2021-11-12 07:18 UTC, SistineFibelKen commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.clickgui": "基于类Windows样点击版GUI(有分类)。",
sry about that , I always thought that was like Windows™ operating system 🤣  (win10 of windows) , Turn out it was like window GUI.

2021-11-12 09:34 UTC, SistineFibelKen commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.masstpa": "给每个人发送tpa请求。\n直到有人接受就会停止\n\n§c§l警告：§r国内服务器使用会因为Wurst判断的是英文而导致tpa仍在继续。",
I will check this more details next weekend.

2021-11-12 09:52 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.bonemealaura": "在指定的作物上自动使用骨粉。\n使用 Checkboxes 来指定作物。",
It's just a box like this:

- [X] checked
- [ ] not checked

2021-11-12 10:13 UTC, SistineFibelKen commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.clickgui": "基于类Windows样点击版GUI(有分类)。",
Forget to fix this clickgui description 🤣

2021-11-12 10:19 UTC, Alexander01998 approved these changes
All fixed as far as I can tell.

2021-11-12 10:21 UTC, SistineFibelKen commented
> All fixed as far as I can tell.

thanks for that , maybe it was the finally version , should I leave e-mail address in the text ?

2021-11-12 10:22 UTC, Alexander01998 commented
@FeyXieXzf @SiongSng how is the Chinese grammar now?

2021-11-12 10:23 UTC, Alexander01998 commented
@Aikini you did the Chinese translations for Mo Glass. I thought you might want to join this conversation as well.

2021-11-12 11:09 UTC, Aikini commented
> @Aikini you did the Chinese translations for Mo Glass. I thought you might want to join this conversation as well.

I don't have enough time to examine them lately, but they may looks fine in grammar.

2021-11-13 07:43 UTC, FeyXieXzf commented
I think there are still some translations need to be fixed. Also, you need to add spaces between Chinese words and English words, like the description in AntiBlind.

2021-11-13 07:43 UTC, FeyXieXzf commented
And still some weird grammar mistake.

2021-11-13 08:04 UTC, Alexander01998 commented
> And still some weird grammar mistake.

Can you please give specific examples of this? Maybe post a review with comments on the affected lines.

2021-11-13 08:09 UTC, FeyXieXzf commented
For the space mistake, line 4.
For the weird words, line 34, it says "Checker" instead of "Checkboxes"

2021-11-13 08:10 UTC, FeyXieXzf commented
Also, in line 53, it should just say "Nuker" instead of "the Nuker function".

2021-11-13 08:31 UTC, Alexander01998 commented
> For the space mistake, line 4.

Fixed.

> For the weird words, line 34, it says "Checker" instead of "Checkboxes"
> Also, in line 53, it should just say "Nuker" instead of "the Nuker function".

@SistineFibelKen

2021-11-13 08:57 UTC, SistineFibelKen commented
> Also, in line 53, it should just say "Nuker" instead of "the Nuker function".

`允许你更快的破坏方块。\n提示：可以和 Nuker 功能配合利用。` 

` Nuker 功能。` is mean that "Nuker function"

Are u sure u r come from China...?🤔(just my personal question) @FeyXieXzf 

> For the weird words, line 34, it says "Checker" instead of "Checkboxes"

fixed. @Alexander01998

2021-11-15 13:20 UTC, merged