japanese
Wurst-Imperium/Wurst7 pull request #503
Opened 2021-11-28 06:56 UTC by sabaadmin

Japanese translation

2021-11-28 06:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=503) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=503) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=503) it.</sub>

2021-11-28 06:59 UTC, buiawpkgew1 commented
why close?

2021-11-28 07:11 UTC, sabaadmin commented
> why close?

I didn't know how to label it.
sorry...

2021-12-08 14:56 UTC, Alexander01998 requested changes

2021-12-08 14:56 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/ja_jp.json
> +    "description.wurst.hack.protect": "最も近いエンティティを追跡し、他のエンティティから保護するボット。\nUse .protectは、最も近いエンティティではなく特定のエンティティを保護します。",
The word "use" is still in English here. Please fix.

2021-12-08 14:56 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/ja_jp.json
> +    "description.wurst.hack.rainbowui": "§cM§aa§9k§ce§as §9e§cv§ae§9r§cy§at§9h§ci§an§9g §cc§ao§9l§co§ar§9f§cu§al§9.",
This description is still in English. Please translate it to Japanese.

(It says "Makes everything colorful." with each character encoded in a different color. The `§c`, `§a`, `§9` are color codes, the rest is text.)

2021-12-08 14:56 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/ja_jp.json
> +    "description.wurst.hack.speedhack": "スプリントやジャンプと比べて2.5倍の速さで走ることができます。\n\n§6§l警告:§r NoCheat+のバージョン3.13.2でパッチが当てられました。古いバージョンのNoCheat+をバイパスするだけです。\nType §l/ncp version§r を入力すると、サーバーのNoCheat+バージョンを確
The word "type" is still in English here. Please fix.

2021-12-08 14:56 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/ja_jp.json
> +    "description.wurst.hack.tillaura": "土や草などを自動的に農地にします。\nKillauraと一緒に使用してはいけません。",
Does this say "Do not use with Killaura"? It should say "Do not _confuse_ with Killaura" instead.

2021-12-08 15:01 UTC, Alexander01998 commented
Can someone who natively speaks Japanese please review this and tell me if it's grammatically correct?

2021-12-11 19:26 UTC, Alexander01998 commented
@sabaadmin Nothing has changed since my last review. Maybe you forgot to upload/push your changes?

2021-12-12 12:56 UTC, sabaadmin commented
Fixed the problem

2021-12-12 13:01 UTC, sabaadmin commented
> @sabaadmin Nothing has changed since my last review. Maybe you forgot to upload/push your changes?

Sorry for the delay in fixing.
I was too busy to do that.

2021-12-12 20:23 UTC, Alexander01998 approved these changes

2021-12-12 20:25 UTC, merged