new feature: Warehouse
Wurst-Imperium/Wurst7 pull request #521
Opened 2021-12-20 11:57 UTC by MineYuanlu

## Description
a new feature: warehosue
it can auto sort all the chest which you want: #518 

## screenshots / videos
![图片](https://user-images.githubusercontent.com/38997444/146762743-f04482b7-2cec-4420-a3da-d4f0e09adcdd.png)

[video](https://youtu.be/3KW7rgOgZc0)

2021-12-20 12:00 UTC, MineYuanlu commented
@Alexander01998  I really want your opinion. I don't know how this idea is.

2021-12-26 16:04 UTC, KTibow requested changes
This looks mostly good. It looks like you accidentally set the version to 1.18 instead of 1.18.1, so I fixed that. Also I had a couple of style tweaks.

2021-12-26 16:04 UTC, KTibow commented on gradle.properties
> +yarn_mappings=1.18+build.1
```suggestion
minecraft_version=1.18.1
yarn_mappings=1.18.1+build.2
```

2021-12-26 16:04 UTC, KTibow commented on gradle.properties
> +mod_version = v7.19-MC1.18
```suggestion
mod_version = v7.19-MC1.18.1
```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/WurstClient.java
> +	public static final String MC_VERSION = "1.18";
```suggestion
	public static final String MC_VERSION = "1.18.1";
```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/command/CmdList.java
> +	public final WarehouseCmd warehouseCmd=new WarehouseCmd();
```suggestion
	public final WarehouseCmd warehouseCmd = new WarehouseCmd();

```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/mixin/ClientPlayNetworkHandlerMixin.java
> +
```suggestion
```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/mixin/ContainerScreen54Mixin.java
>  			onMouseClick(slot, slot.id, 0, SlotActionType.QUICK_MOVE);
```suggestion

			onMouseClick(slot, slot.id, 0, SlotActionType.QUICK_MOVE);
```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/mixin/ShulkerBoxScreenMixin.java
> +			WurstClient.INSTANCE.getCmds().warehouseCmd;
```suggestion
		WurstClient.INSTANCE.getCmds().warehouseCmd;
```

2021-12-26 16:04 UTC, KTibow commented on src/main/java/net/wurstclient/mixin/ShulkerBoxScreenMixin.java
> +		if (warehouse.callbackOpenWindow(handler.syncId,rows*9)) return;
```suggestion
		if (warehouse.callbackOpenWindow(handler.syncId, rows*9)) return;

```

2021-12-27 02:31 UTC, MineYuanlu commented
> This looks mostly good. It looks like you accidentally set the version to 1.18 instead of 1.18.1, so I fixed that. Also I had a couple of style tweaks.

I am very grateful to you for helping me solve these problems! 😁 😁

2021-12-27 02:54 UTC, KTibow commented
Now, given that Wurst tends to be more inactive, I think it would be a good idea if you could upload a build of Wurst with your feature publicly, while you wait for them to merge your pull request.

2021-12-27 02:55 UTC, MineYuanlu commented
> Now, given that Wurst tends to be more inactive, I think it would be a good idea if you could upload a build of Wurst with your feature publicly, while you wait for them to merge your pull request.

OK, I'll upload it after I fix all the known problems.

2021-12-28 06:54 UTC, MineYuanlu commented
I think there are problems with some operations on git branch in the past. I will restart the pull request after finishing the code. The code has moved to a new branch: [new branch - warehouse](https://github.com/MineYuanlu/Wurst7/tree/warehouse)

2021-12-28 06:54 UTC, closed without merging

2021-12-28 15:15 UTC, KTibow commented
That branch looks good. Make sure to let me know when you're finished by putting the text "@KTibow" in your pull request.

2021-12-30 14:34 UTC, MineYuanlu commented
@KTibow 


Look here: https://github.com/MineYuanlu/Wurst7/releases  
I have a little time today. I fixed some bugs and sorted out some things

2021-12-30 16:35 UTC, KTibow commented
I'll look at it soon. Thanks.

2021-12-30 16:51 UTC, KTibow commented
@MineYuanlu Can you upload a video of you configuring Warehouse, without any previous configuration? I can't figure out how to get started.

2021-12-30 16:57 UTC, KTibow commented
Also I would recommend changing the description for TradeFill to:
```
Automatically inserts emeralds into the villager trade menu.
```

2021-12-31 04:24 UTC, MineYuanlu commented
> @MineYuanlu Can you upload a video of you configuring Warehouse, without any previous configuration? I can't figure out how to get started.

[warehouse wiki](https://github.com/MineYuanlu/Wurst7/wiki/Warehouse)

I made a simple wiki page.
My English is not very good. Most of them use machine translation and may not be able to express my meaning clearly.

2021-12-31 14:15 UTC, KTibow commented
How do you specify the item list for an output chest?

2021-12-31 16:28 UTC, MineYuanlu commented
> How do you specify the item list for an output chest?

Oh, sorry, I forgot to say. Put items in the box, and then enter the sign mode. Right click the box to mark.

Now Beijing time (UTC + 8) has just entered a new year. Happy New Year!

2021-12-31 16:55 UTC, KTibow commented
I would recommend changing
```
.warehouse sign <type> [w] [io] [a] Enable container tagging
```
to
```
.warehouse markmode <type> [priority] [maxAmountMode] [maxAmount] Go into marking mode
```

2021-12-31 16:59 UTC, KTibow commented
Also, maybe default maxAmountMode and amount to item and -27. Other than that, I got this to work, which seems really cool.

2022-01-01 04:38 UTC, MineYuanlu commented
> I would recommend changing
> 
> ```
> .warehouse sign <type> [w] [io] [a] Enable container tagging
> ```
> 
> to
> 
> ```
> .warehouse markmode <type> [priority] [maxAmountMode] [maxAmount] Go into marking mode
> ```

well! I have modified the content of the wiki, and the tips in the game will be modified in the next version



> Also, maybe default maxAmountMode and amount to item and -27. Other than that, I got this to work, which seems really cool.

At present, the default `maxAmountMode` is `item` and `maxAmount` is `0`. I think `maxAmount` in `storage` mode should be changed to `-54`(considering the double-chest, it should not be `-27`), and others should remain unchanged. What's your opinion?

2022-01-01 14:05 UTC, KTibow commented
> well! I have modified the content of the wiki, and the tips in the game will be modified in the next version

Sounds good.

> think maxAmount in storage mode should be changed to -54(considering the double-chest, it should not be -27), and others should remain unchanged. What's your opinion?

Well, what would happen if you try to use `-54` on a single chest? Would anything break?

2022-01-01 14:08 UTC, MineYuanlu commented
> Well, what would happen if you try to use `-54` on a single chest? Would anything break?

No, the program will detect whether it can be stored. This mechanism is a little complex, but I think there is no problem. I have tested it for a long time.

Then, can we exchange other contact information? I don't think it's good to communicate here.

2022-01-01 14:39 UTC, KTibow commented
> No, the program will detect whether it can be stored. This mechanism is a little complex, but I think there is no problem. I have tested it for a long time.
Then, can we exchange other contact information? I don't think it's good to communicate here.

Alright, that sounds good. I'm KTibow#3960 on Discord, feel free to send a friend request.