Create uk_ua.json
Wurst-Imperium/Wurst7 pull request #526
Opened 2021-12-26 16:18 UTC by KTibow

Co-authored-by: xVirum <xVirum@users.noreply.github.com>
Co-authored-by: MrYotic <MrYotic@users.noreply.github.com>

## Description
Adds a Ukraine translation. Requested by MrYotic, translated by xVirum, fixed into valid JSON by me.

## (Optional) screenshots / videos
Not tested since I don't know how to build Wurst.

2022-01-08 17:23 UTC, Alexander01998 requested changes

2022-01-08 18:22 UTC, xVirum commented on src/main/resources/assets/wurst/lang/uk_ua.json
> +  "description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайні виглядають більш підозріло, ніж Killaura'и і легше виявляють
\n\n§c§lУВАГА:§r ClickAura'и звичайні виглядають більш підозріло, ніж Killaura'и і легше виявляються плагінами. використовувати Killaura або TriggerBot. 
This is in the text now
![text](https://user-images.githubusercontent.com/96312105/148655305-9f8b2ab4-3aef-4213-906c-fc36c79ba56e.PNG)

2022-01-08 18:27 UTC, xVirum commented on src/main/resources/assets/wurst/lang/uk_ua.json
> +  "description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайні виглядають більш підозріло, ніж Killaura'и і легше виявляють
There is a warning in the text, but its translation is inaccurate, I will correct it soon.

2022-01-08 18:38 UTC, MrYotic commented
[uk-UA.txt](https://github.com/Wurst-Imperium/Wurst7/files/7833787/uk-UA.txt)
I fixed that

2022-01-08 18:43 UTC, xVirum commented on src/main/resources/assets/wurst/lang/uk_ua.json
> +  "description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайні виглядають більш підозріло, ніж Killaura'и і легше виявляють
fixed in @MrYotic txt file

2022-01-08 18:44 UTC, KTibow commented on src/main/resources/assets/wurst/lang/uk_ua.json
> +  "description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайні виглядають більш підозріло, ніж Killaura'и і легше виявляють
```suggestion
  "description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайно виглядають більш підозріло, ніж Killaura'и і легше виявляються плагінами. Краще використовувати Killaura або TriggerBot.",
```

2022-01-08 18:48 UTC, xVirum commented
fixed.

2022-01-09 16:24 UTC, Alexander01998 approved these changes

2022-01-09 16:26 UTC, merged