Add fr_fr.json
Wurst-Imperium/Wurst7 pull request #531
Opened 2022-01-02 16:20 UTC by mystere1337

## Description
Added localization file for French (fr_fr.json).

2022-01-02 16:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=531) it.</sub>

2022-01-11 21:03 UTC, sivelswhy commented
You got ahead of me, I had the translation, but I forgot to upload it lmao

2022-01-12 13:09 UTC, mystere1337 commented
Haha, there is currently another french translation in the queue but it is lacking some strings that's why I made this one.

2022-02-09 15:29 UTC, TranslatorEnglishToFrench requested changes
Bonjour ! J'ai tchecker cette traduction et il y a quelques erreurs que j'aimerais bien revoir avec toi ou simplement me permette de les changer ! 

Hi, there are some grammar errors or just context, it looks pretty good to me overall but it needs to be reviewed before adding it!

2022-02-09 16:38 UTC, TranslatorEnglishToFrench requested changes
Here are the changes to be made to the file before accepting it!

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.chattranslator": "Traduit les messages du chat avec Google Traduction.",
"description.wurst.hack.chattranslator": "Traduit les messages du tchat avec Google Traduction.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.chestesp": "Surligne les coffres à proximité.",
"description.wurst.hack.chestesp": "Met en surbrillance les coffres à proximité.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.crashchest": "Génère un coffre banissant les joueurs du serveur s'ils ont trop de copies de ce coffre dans leur inventaire. §c§lAVERTISSEMENT:§r §cCela ne peut être défait
"description.wurst.hack.crashchest": "Génère un coffre bannissant les joueurs du serveur s'ils ont trop de copies de ce coffre dans leur inventaire. §c§lAVERTISSEMENT:§r §cCela ne peut être défait. Utilisez avec précaution!§r\n\nSi des copies sont placées dans un coffre à la place, n'importe quel joueur l'ouvrant sera exclu du serveur (juste une fois).",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.creativeflight": "Vous permet de voler comme en mode créatif.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégats si vous n'activez pas NoFall.",
"description.wurst.hack.creativeflight": "Vous permet de voler comme en mode créatif.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts de chute si vous n'activez pas NoFall.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.crystalaura": "Place automatiquement (optionnel) et fait explose des crystaux de l'end afin de tuer des joueurs autour de vous.",
"description.wurst.hack.crystalaura": "Place automatiquement (optionnel) et fait exploser des cristaux de l'end afin de tuer des joueurs autour de vous."

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.excavator": "Détruit automatiquement tous les blocs dans l'aire séléctionnée.",
"description.wurst.hack.excavator": "Détruit automatiquement tous les blocs dans l'aire sélectionnée.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.extraelytra": "Les elytres deviennent plus faciles à utliser.",
"description.wurst.hack.extraelytra": "Les élytres deviennent plus faciles à utiliser.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.fancychat": "Remplace les caractères ASCII dans le chat par de jolis caractères unicodes. Peut être utilisé pour contourner les filtres à insultes sur certains serveurs.\n
"description.wurst.hack.fancychat": "Remplace les caractères ASCII dans le chat par de jolis caractères unicodes. Peut être utilisé pour contourner les filtres à insultes sur certains serveurs.\nNe fonctionne pas sur les serveurs bloquants les caractères unicodes.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.feedaura": "Nourrit automatiquement tout mob autour de vous",
"description.wurst.hack.feedaura": "Nourrit automatiquement les animaux autour de vous",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.flight": "Vous permet de volder.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégats si vous n'activez pas NoFall.",
"description.wurst.hack.flight": "Vous permet de voler.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts de chute si vous n'activez pas NoFall.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.glide": "Vous fait lentement glisser vers le bas lorsque vous tombez.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégats si vous n'activez pas NoFall.",
"description.wurst.hack.glide": "Vous fait lentement glisser vers le bas lorsque vous tombez.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts de chute si vous n'activez pas NoFall.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.highjump": "Vous permet de souter plus haut.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégats si vous n'activez pas NoFall.",
"description.wurst.hack.highjump": "Vous permet de souter plus haut.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts de chute si vous n'activez pas NoFall.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.instantbunker": "Construit un petit abri autour de vous. Nécéssite 57 blocs.",
"description.wurst.hack.instantbunker": "Construis un bunker autour de vous. Nécessite 57 blocs.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.itemesp": "Surligne les objets proches.",
"description.wurst.hack.itemesp": "Met en surbrillance les items à proximité.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.jetpack": "Vous permet de vous déplacer comme si vous aviez un jetpack.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégats si vous n'activez pas NoFall.",
"description.wurst.hack.jetpack": "Vous permet de vous déplacer comme si vous aviez un jetpack.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts de chute si vous n'activez pas NoFall.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.killpotion": "Génère une potion pouvant tuer presque tout, y compris les joueurs en mode créatif. Ne fonctionne pas sur les mobs mort-vivants, puisqu'ils sont déja morts.\
"description.wurst.hack.killpotion": "Génère une potion pouvant tuer presque tout, y compris les joueurs en mode créatif. Ne fonctionne pas sur les mobs mort-vivants, puisqu'ils sont déjà morts.\n\nMode créatif requis.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.mobesp": "Surligne les mobs proches.",
"description.wurst.hack.mobesp": "Met en surbrillance les monstres à proximité.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.mobspawnesp": "Surligne les aires de spawn de mobs.\n§eyellow§r - les mobs peuvent apparaître pendant la nuit\n§cred§r - les mobs peuvent toujours apparaitre",
"description.wurst.hack.mobspawnesp": "Met en surbrillance les zones où les monstres peuvent apparaître.\n§eJaune§r - les monstres peuvent apparaître la nuit\n§cRouge§r - les monstres peuvent toujours apparaître",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.nobackground": "Désactive l'arrière plan sombre derrière les interfaces.",
"description.wurst.hack.nobackground": "Désactiver l'arrière plan sombre derrière les interfaces.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.noclip": "Vous permet de vous déplacer librement à travers les blocs.\nUn bloc (ex: sable) doit tomber sur votre tête pour l'activer.\n\n§c§lAVERTISSEMENT:§r Vous prendrez
"description.wurst.hack.noclip": "Vous permet de vous déplacer librement à travers les blocs.\nUn bloc (ex: sable) doit tomber sur votre tête pour l'activer.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts en vous déplaçant à travers les blocs!",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.nofireoverlay": "Bloque l'effet de caméra lorsque vous êtes en feu.\n\n§c§lAVERTISSEMENT:§r Vous pouvez mourrir par immolation sans vous en apercevoir.",
"description.wurst.hack.nofireoverlay": "Bloque l'effet de caméra lorsque vous êtes en feu.\n\n§c§lAVERTISSEMENT:§r Vous pouvez mourir par immolation sans vous en apercevoir.",

2022-02-09 16:38 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.tunneller": "Creuse automatiquement un tunnel.\n\n§c§lAVERTISSEMENT:§r Malgé le fait que le bot essayera d'éviter la lave et autres dangers, il n'est pas garanti qu'il ne
"description.wurst.hack.tunneller": "Creuse automatiquement un tunnel.\n\n§c§lAVERTISSEMENT:§r Malgré le fait que le bot essayera d'éviter la lave et autres dangers, il n'est pas garanti qu'il ne mourra pas. Utilisez uniquement cette option avec un équipement que vous pouvez perdre.",

2022-02-09 18:11 UTC, TranslatorEnglishToFrench requested changes
Correction of an error while rereading the file

2022-02-09 18:11 UTC, TranslatorEnglishToFrench commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.antiafk": "Vous fait vous déplacer automatiquement afin de ne vous faire exclure pour AFK.\nNécéssite une surface minimum de 3x3 blocs.",
"description.wurst.hack.antiafk": "Ce bot vous fait déplacer automatiquement afin de ne vous faire exclure pour AFK.\nNécessite une surface minimum de 3x3 blocs.",

2022-03-05 23:36 UTC, VizardAlpha commented
Good evening, the translation looks good, we just have to make the changes suggested by @TranslatorEnglishToFrench.

2022-03-05 23:40 UTC, VizardAlpha requested changes

2022-03-05 23:40 UTC, VizardAlpha commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.anticactus": "Vous protège des dégats des cactus",
"description.wurst.hack.anticactus": "Vous protège des dégâts des cactus.",

2022-03-05 23:40 UTC, VizardAlpha commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.antiwobble": "Supprime l'effet de caméra causé par la nausée et les protails du nether",
"description.wurst.hack.antiwobble": "Supprime l'effet de caméra causé par la nausée et les portails du nether.",

2022-03-05 23:40 UTC, VizardAlpha commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.feedaura": "Nourrit automatiquement tout mob autour de vous",
"description.wurst.hack.feedaura": "Nourrit automatiquement les animaux autour de vous.",

2022-03-05 23:40 UTC, VizardAlpha commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.mobspawnesp": "Surligne les aires de spawn de mobs.\n§eyellow§r - les mobs peuvent apparaître pendant la nuit\n§cred§r - les mobs peuvent toujours apparaitre",
"description.wurst.hack.mobspawnesp": "Met en surbrillance les zones où les monstres peuvent apparaître.\n§eJaune§r - les monstres peuvent apparaître la nuit\n§cRouge§r - les monstres peuvent toujours apparaître.",

2022-03-05 23:40 UTC, VizardAlpha commented on src/main/resources/assets/wurst/lang/fr_fr.json
> +    "description.wurst.hack.noclip": "Vous permet de vous déplacer librement à travers les blocs.\nUn bloc (ex: sable) doit tomber sur votre tête pour l'activer.\n\n§c§lAVERTISSEMENT:§r Vous prendrez
"description.wurst.hack.noclip": "Vous permet de vous déplacer librement à travers les blocs.\nUn bloc (ex: sable) doit tomber sur votre tête pour l'activer.\n\n§c§lAVERTISSEMENT:§r Vous prendrez des dégâts en vous déplaçant à travers les blocs !",

2023-12-11 02:08 UTC, closed without merging