Italian translation
Wurst-Imperium/Wurst7 pull request #544
Opened 2022-01-15 19:58 UTC by RENNAARENATA

## Description
Added an italian translation^^

2022-01-15 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=544) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=544) it.</sub>

2022-01-21 18:06 UTC, Alexander01998 requested changes

2022-01-22 09:24 UTC, RENNAARENATA commented on src/main/resources/assets/wurst/lang/it_IT.json
> +  "description.wurst.hack.radar": "Mostra la posizione delle entità vicine.\n§cred§r - Giocatori\n§6orange§r - Mostri\n§agreen§r - Animali\n§7gray§r - Altro",
Done^^

2022-01-23 12:29 UTC, Alexander01998 approved these changes

2022-01-23 12:31 UTC, merged