Add nocom crash
Wurst-Imperium/Wurst7 pull request #560
Opened 2022-01-27 23:45 UTC by AidanRB

## Description
Uses the nocom exploit to cause servers to load lots of chunks at once and lag a lot, or even crash

## (Optional) screenshots / videos
[Not my video but this is it](https://www.youtube.com/watch?v=f0pT6rJnrCA)

2022-01-27 23:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=560) it.</sub>

2022-01-28 03:42 UTC, Alexander01998 requested changes
Please clarify exactly what type of servers this hack is compatible with. I need this info for documentation and to set up test servers.

2022-01-28 03:42 UTC, Alexander01998 commented on src/main/resources/assets/wurst/lang/en_us.json
> +  "description.wurst.hack.nocomcrash": "Lags servers using the nocom exploit.\nDoes not work on Paper servers.",
If I understand correctly this exploit only works on Spigot servers. If so, the description should mention that.

2022-01-28 03:42 UTC, Alexander01998 commented on src/main/java/net/wurstclient/hacks/NocomCrashHack.java
> +		"1.18.1" })
Is this really exclusive to 1.18.1? I thought the NoCom exploit was used on the 2b2t server running 1.12.2?

2022-01-28 04:19 UTC, AidanRB commented
From my testing, this works on vanilla, spigot, and fabric servers. Paper has it patched. I don't know what versions it works on, except that it works in 1.18.1. I assume it works for many older versions as well. I'll try to stand up some test servers and test it out this weekend.

2022-01-29 00:37 UTC, AidanRB commented
Added clearer documentation on the tested working server types

2022-02-01 03:11 UTC, Alexander01998 approved these changes

2022-02-01 15:02 UTC, merged

2022-02-11 04:45 UTC, Saturn5Vfive commented
This hack was originall made by my friend 0x150 (his github got locked) You should at least add credit to him somewhere instead of this guy who did almost 0 work pasting the code into wurst.

2022-02-11 05:31 UTC, 0x3C50 commented
Yeah I was about to say, this is my content, and I do not want this here. Can we speak in private about this? 0x150 the 2nd#0150

2022-02-11 10:09 UTC, Alexander01998 commented
@0x3C50

1. @AidanRB has signed a legally binding [agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=560) to confirm that this hack is either their original creation, or that they have all the necessary rights to submit this hack and have pointed out any original sources, licenses, or restrictions that they are aware of.
2. Copyright only applies to actual work, not to abstract ideas. You cannot copyright the idea of a NocomCrash hack, just like nobody can copyright the idea of a Killaura, or a Minecraft Hacked Client. Copyright applies when someone literally copies another person's work.
3. Looking at [your implementation](https://github.com/0x3C50/Coffee/blob/master/src/main/java/me/x150/sipprivate/feature/module/impl/exploit/NoComCrash.java), it looks substantially different from what was [submitted here](https://github.com/Wurst-Imperium/Wurst7/pull/560/files). Neither version seems to be a direct copy of the other. The only parts that are the same are the ones that have to be the same in order for the hack to function.
4. For example, @AidanRB's version does not use an ItemStack or CreativeInventoryActionC2SPacket, while your version does not use a separate Thread. I am confident that @AidanRB has put their own work into developing and testing this hack, and there is clear evidence to support this.

2022-02-11 11:39 UTC, AidanRB commented
@0x3C50 Hey, trying to add you but you have friend requests off. My intention was not to steal your code, I was under the impression you were okay with it. If I can add you we can talk.

2022-02-11 22:48 UTC, 0x3C50 commented
> @0x3C50
> 
>     1. @AidanRB has signed a legally binding [agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=560) to confirm that this hack is either their original creation, or that they have all the necessary rights to submit this hack and have pointed out any original sources, licenses, or restrictions that they are aware of.
> 
>     2. Copyright only applies to actual work, not to abstract ideas. You cannot copyright the idea of a NocomCrash hack, just like nobody can copyright the idea of a Killaura, or the idea of a Minecraft Hacked Client. Copyright applies when someone literally copies another person's work.
> 
>     3. Looking at [your implementation](https://github.com/0x3C50/Coffee/blob/master/src/main/java/me/x150/sipprivate/feature/module/impl/exploit/NoComCrash.java), it looks substantially different from what was [submitted here](https://github.com/Wurst-Imperium/Wurst7/pull/560/files). Neither version seems to be a direct copy of the other. The only parts that are the same are the ones that have to be the same in order for the hack to function.
> 
>     4. For example, @AidanRB's version does not use an ItemStack or CreativeInventoryActionC2SPacket, while your version does not use a separate Thread. I am confident that @AidanRB has put their own work into developing and testing this hack, and there is clear evidence to support this.

My mod has 2 different modes, both of them work essentially the same. The same concept was applied here, even copying the random method name and the variable it gets saved under:

This implementation
![image](https://user-images.githubusercontent.com/99053360/153681036-6541ee3f-a1c3-42f8-8456-5a5cd7bd867f.png)
![image](https://user-images.githubusercontent.com/99053360/153681128-1281540f-8871-48a3-a24e-4ce37550b92a.png)


The original
![image](https://user-images.githubusercontent.com/99053360/153681049-f3c90418-e78c-40a1-ac4c-3757dda6b3ac.png)
![image](https://user-images.githubusercontent.com/99053360/153681117-5dfba71c-78ac-4e53-b1fd-ab9928d8e222.png)

2022-02-11 22:49 UTC, 0x3C50 commented
> @0x3C50 Hey, trying to add you but you have friend requests off. My intention was not to steal your code, I was under the impression you were okay with it. If I can add you we can talk. crisp#5610

Also sorry for taking so long, sent the friend request

2022-02-11 23:06 UTC, 0x3C50 commented
@Alexander01998 can we go into a vc and discuss this please? This is becoming very interesting very fast.

2022-02-12 08:51 UTC, Alexander01998 commented
@0x3C50 @Saturn5Vfive No, I will not go into voice chat with you. I have seen enough of your disrespectful and immature behavior in the comments above. Either you figure this out with @AidanRB or we're done here.