Update zh_cn.json
Wurst-Imperium/Wurst7 pull request #588
Opened 2022-02-25 15:54 UTC by Clexus

修改了一些语法错误和加了一些小细节
Fixed some grammatical errors and add some details

2022-02-25 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Wurst-Imperium/Wurst7?pullRequest=588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Wurst-Imperium/Wurst7?pullRequest=588) it.</sub>

2022-04-03 16:08 UTC, Clexus commented
can I be the proofreader?

2022-04-06 20:04 UTC, Alexander01998 commented
> can I be the proofreader?

You cannot be the proofreader of your own translation. You can only proofread other people's translations.

2022-07-11 09:17 UTC, xtexChooser requested changes
Good Job

2022-07-11 09:17 UTC, xtexChooser commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.kaboom": "像爆炸一样破坏你附近的方块。\n这个可能比 Nuker 功能破坏更快，如果服务器没有反作弊的话，使用适合的工具和破坏脆弱的方块可以事半功倍。\n注意：这并不是真正的爆炸。",
条件放前面好点吧（

2022-07-11 09:17 UTC, xtexChooser commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.noslowdown": "取消减速的效果。像蜂蜜、灵魂沙或者使用物品时。",
“蜂蜜、灵魂沙”建议加个动词

2022-07-11 09:17 UTC, xtexChooser commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.throw": "迅速丢出你手中种类的物品，可以用于丢雪球、鸡蛋、刷怪蛋、矿车，诸如此类。\n\n会生成大量的该种实体，这会产生大幅的卡顿且可能会导致服务器崩溃。",
“手中种类的物品”？

2022-07-11 09:17 UTC, xtexChooser commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.tunneller": "自动挖一个隧道。\n\n§c§l警告：§r 尽管这个 AI 会自动避开岩浆和其他危险的地方，但这里没有守卫确保你不会死亡，除非你不介意你所有的东西都有可能因此失去。",
“会自动”应该是“会尝试”（”will try to“）
“守卫”应该是“保证”（“guarantee”）

2022-07-31 00:50 UTC, buiawpkgew1 commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.throw": "迅速丢出你手中种类的物品，可以用于丢雪球、鸡蛋、刷怪蛋、矿车，诸如此类。\n\n会生成大量的该种实体，这会产生大幅的卡顿且可能会导致服务器崩溃。",
"主手中" ?

2022-07-31 00:54 UTC, xtexChooser commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.throw": "迅速丢出你手中种类的物品，可以用于丢雪球、鸡蛋、刷怪蛋、矿车，诸如此类。\n\n会生成大量的该种实体，这会产生大幅的卡顿且可能会导致服务器崩溃。",
原文是多次使用同一种物品，不一定是丢，但是确实用的是主手

2022-07-31 00:54 UTC, xtexChooser commented
cc @Clexus

2022-07-31 15:35 UTC, Alexander01998 commented
@xtexChooser This pull request was abandoned in April and many of its translations now conflict with the master branch. I don't think this will get merged anymore...

2022-08-05 04:52 UTC, Clexus commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.tunneller": "自动挖一个隧道。\n\n§c§l警告：§r 尽管这个 AI 会自动避开岩浆和其他危险的地方，但这里没有守卫确保你不会死亡，除非你不介意你所有的东西都有可能因此失去。",
我直接按照错误翻译来的，没看原文

2022-08-05 04:52 UTC, Clexus commented on src/main/resources/assets/wurst/lang/zh_cn.json
> +  "description.wurst.hack.tunneller": "自动挖一个隧道。\n\n§c§l警告：§r 尽管这个 AI 会自动避开岩浆和其他危险的地方，但这里没有守卫确保你不会死亡，除非你不介意你所有的东西都有可能因此失去。",
> “会自动”应该是“会尝试”（”will try to“） “守卫”应该是“保证”（“guarantee”）

x

2023-07-25 02:02 UTC, closed without merging