Make X-Ray fully compatible with Sodium
Wurst-Imperium/Wurst7 pull request #889
Opened 2023-10-22 20:06 UTC by ZANX3Y

## Description
Made X-Ray fully compatible with Sodium.
Liquids, plants, etc. now work the same way as in Vanilla.
Completes #458

2023-10-22 20:22 UTC, ZANX3Y commented on src/main/java/net/wurstclient/mixin/SodiumBlockRendererMixin.java
> +            cir.setReturnValue(List.of());
The `isRendered` method is just a getter.

2023-10-25 12:12 UTC, Alexander01998 requested changes
Hey @ZANX3Y, great work on making X-Ray compatible with Sodium! 👍

However, I'm worried that adding Sodium as a dependency might cause problems with future updates, since Sodium doesn't support Minecraft's snapshots and often takes a while to support new releases.

To address this, could you modify the mixins to work without the Sodium dependency, similar to how `SodiumBlockOcclusionCacheMixin` worked previously? This way, we can maintain compatibility with Sodium without directly linking our update cycle to theirs.

Thanks!

2023-10-26 22:04 UTC, ZANX3Y commented
Done. Had to create 3 BakedModel mixins to replace the BlockRenderer mixin, but now it works without having Sodium as a dependency.

2023-10-27 14:29 UTC, Alexander01998 commented on src/main/java/net/wurstclient/hacks/XRayHack.java
> +import net.wurstclient.events.*;
This is fine. @nobotreply

2023-10-28 17:08 UTC, Alexander01998 commented
Hey @ZANX3Y, thanks for the update!

I see why you had to replace the `BlockRenderer` mixin - the `BlockRenderContext` parameter is not accessible without having Sodium as a dependency.

But after doing some testing, it seems we might not actually need all 3 of those `BakedModel` mixins. Specifically, `MultipartBakedModelMixin` and `WeightedBakedModelMixin` don't seem to have any effect on X-Ray's rendering, unless I missed something? All of these blocks still get X-Ray'd correctly with those two mixins removed:

![A screenshot showing various blocks with X-Ray disabled.](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/7675f329-6e63-4033-9652-062e4055fda4)

![A screenshot from the same angle but with X-Ray enabled. All of the various blocks have turned invisible.](https://github.com/Wurst-Imperium/Wurst7/assets/10100202/dce19277-42da-4ee7-822d-a6a0ed3461c8)

Please let me know if you've run into any blocks or scenarios that don't work properly without these mixins. Otherwise, let's remove them to simplify the logic.

Also, I found that `BasicBakedModelMixin` actually works even when Sodium isn't installed. If we remove the stack trace check that filters out non-Sodium method calls, this mixin can replace `TerrainRenderContextMixin` and thereby further simplify the X-Ray code.

In theory, this would even make `BlockModelRendererMixin` redundant. This mixin does pretty much the same things as `TerrainRenderContextMixin`, but only when OptiFine is installed. Since OptiFine is not yet available for Minecraft 1.20.2, I can't 100% confirm this right now.

I'll await your response before making these changes, just in case I got anything wrong here.

2023-10-28 19:34 UTC, ZANX3Y commented
Hi @Alexander01998, looks like you're right.

I flew around the "Debug mode" world and confirmed that both `MultipartBakedModelMixin` and `WeightedBakedModelMixin` are actually not needed.

I also tried removing the stack trace check and `TerrainRenderContextMixin` as you suggested. It seems that `BasicBakedModelMixin` handles everything well for Sodium and vanilla renderer.

As for the `BlockModelRendererMixin`, I suspect that it should be redundant, unless OptiFine does some sort of caching of the model quads.

Cheers

2023-10-29 13:32 UTC, Alexander01998 approved these changes

2023-10-29 13:40 UTC, merged