Add MassTpahere
Wurst-Imperium/Wurst7 pull request #899
Opened 2023-11-07 06:26 UTC by JAXPLE

## Description
I want to terrorize tphere.

## (Optional) screenshots / videos
<img width="966" alt="스크린샷 2023-11-07 15 25 10" src="https://github.com/Wurst-Imperium/Wurst7/assets/114869036/ddf1a0f9-1b0d-49dd-b08c-f3af8e2a33a5">

2023-11-07 09:18 UTC, Alexander01998 requested changes
Using a `CheckboxSetting` to select the command might be rather unintuitive to the user. It would also limit customization to only these two commands, while some players might want to select other commands like `/tp` or `/tpo`.

I think it would be better to use a `TextFieldSetting` instead.

2023-11-08 06:56 UTC, JAXPLE commented
@Alexander01998 
I'll edit it and upload it again and tag you.

2023-11-08 07:51 UTC, JAXPLE commented
@Alexander01998 
It went faster than I thought

2023-11-13 20:05 UTC, Alexander01998 approved these changes

2023-11-16 07:49 UTC, merged